#include <stdio.h>
#include "msg.h"				/* msg.h generated by rpcgen */
 
 int * 
 printmessage_1(msg, clnt)
	char ** msg; 
    CLIENT * clnt;
{
	printf("%s\n", msg);
	return(1);
}


int *
printmessage_1_svc(msg, req)
	char **msg;	
	struct svc_req *req;		/* details of call */
{
	printf("%s\n", msg);
	return(1);
}