#include <stdio.h>
#include "msg.h"				/* msg.h generated by rpcgen */
 
 char ** 
 printmessage_1(msg, clnt)
	char ** msg; 
    CLIENT * clnt;
{
	printf("%s\n", *msg);
	
	return msg;
}


char **
printmessage_1_svc(msg, req)
	char **msg;	
	struct svc_req *req;		/* details of call */
{
	printf("%s\n", *msg);

	return msg;
}