/*
 * rprintmsg.c: remote version
 * of "printmsg.c"
 */
#include <stdio.h>
#include "msg.h"			/* msg.h generated by rpcgen */
 
int main(argc, argv)
	int argc;
	char *argv[];
{
	CLIENT *clnt;
	char **responseString;
	char *server;
	char *message;
 
	if (argc != 3) {
		fprintf(stderr, "usage: %s <host> <message>\n", argv[0]);
		exit(1);
	}
 
	server = argv[1];
	message = argv[2];
	/*
	 * Create client "handle" used for 
     * calling MESSAGEPROG on the server
	 * designated on the command line.
	 */
	clnt = clnt_create(server, MESSAGEPROG,
								PRINTMESSAGEVERS,
								"visible");
	if (clnt == (CLIENT *)NULL) {
		/*
		 * Couldn't establish connection
         * with server.
		 * Print error message and die.
		 */
		clnt_pcreateerror(server);
		exit(1);
	}
		/*
	 * Call the remote procedure
  	 * "printmessage" on the server
	 */
	responseString = printmessage_1(&message, clnt);


	if (responseString == (char **)NULL || *responseString == (char *)NULL) {
		/*
		 * An error occurred while calling 
    	 * the server.
		 * Print error message and die.
		 */
		fprintf(stderr,
		"%s: could not print your message\n",argv[0]);
		exit(1);

		clnt_perror(clnt, server);
		exit(1);
	}
	else
	{
		/* The message got printed on the
 		* server's console
 		*/
		printf("Message delivered to %s\n",
				server);

		printf("Reponse from server: %s\r\n", *responseString);
	}

	clnt_destroy( clnt );
	exit(0);

	return 0;	
}